[mgr]
linemode = "size"

[input]
cursor_blink = true

[opener]
edit = [
	# This command sets the environment variable for this specific execution
	# and then launches nvim with the selected file(s) ($@).
	{ run = 'NVIM_APPNAME="nvim-minimal" nvim "$@"', desc = "nvim (minimal)", block = true, for = "unix" },

	# Optional: You can keep the default editor as a second option
	{ run = '${EDITOR:-vim} "$@"', desc = "Default Editor", block = true, for = "unix" },
]
